name: Unity Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_VERSION: 6000.0.3f1
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      # Your existing checkout and Unity installation steps...

      - name: Request Unity License Activation File
        run: |
          # Generate the license request file
          /opt/unity/Editor/Unity -batchmode -nographics -createManualActivationFile

      - name: Upload License Request
        uses: actions/upload-artifact@v3
        with:
          name: Unity_v${{ env.UNITY_VERSION }}.alf
          path: Unity_v${{ env.UNITY_VERSION }}.alf

