name: Unity Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_VERSION: 6000.0.44f1
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Unity installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/unity
          key: ${{ runner.os }}-unity-${{ env.UNITY_VERSION }}

      - name: Get Unity Download Hash
        id: unity_hash
        run: |
          
          JSON_URL="https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json"

          HASH=$(curl -s $JSON_URL | jq -r --arg ver "$UNITY_VERSION" '.official[] | select(.version == $ver) | .downloadUrl' | sed 's|.*download_unity/||;s|/.*||')

          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Download Unity Installer
        run: |
          
          HASH=${{ steps.unity_hash.outputs.hash }}
          
          URL="https://download.unity3d.com/download_unity/${HASH}/UnitySetup-${UNITY_VERSION}"
          echo "Downloading Unity from: $URL"
          
          wget "$URL"
          chmod +x "UnitySetup-${UNITY_VERSION}"

          ./UnitySetup-${UNITY_VERSION} --unattended --install-location /opt/unity --components Unity


      - name: Activate Unity License (Free)
        if: env.UNITY_LICENSE != ''
        run: |
          echo "${UNITY_LICENSE}" > Unity_v${UNITY_VERSION}.ulf
          /opt/unity/Editor/Unity -batchmode -nographics -manualLicenseFile Unity_v${UNITY_VERSION}.ulf || true

      - name: Activate Unity License (Pro)
        if: env.UNITY_SERIAL != ''
        run: |
          /opt/unity/Editor/Unity -batchmode -nographics -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL" -logFile /dev/stdout || true

      # - name: Build Project
      #   run: |
      #     /opt/unity/Editor/Unity -batchmode -nographics -quit \
      #       -projectPath . \
      #       -buildTarget StandaloneLinux64 \
      #       -executeMethod BuildScript.PerformBuild \
      #       -logFile /dev/stdout

      - name: Deactivate Unity License
        if: always()
        run: |
          /opt/unity/Editor/Unity -batchmode -nographics -returnlicense -logFile /dev/stdout || true
