name: Unity Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_VERSION: 6000.0.44f1
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache Unity installation
        uses: actions/cache@v3
        with:
          path: ~/.cache/unity
          key: ${{ runner.os }}-unity-${{ env.UNITY_VERSION }}

      - name: Install Unity
        run: |
          wget https://download.unity3d.com/download_unity/$(echo $UNITY_VERSION | tr '.' '_')/UnitySetup
          chmod +x UnitySetup
          ./UnitySetup --unattended --install-location /opt/unity --version $UNITY_VERSION

      - name: Activate Unity License (Free)
        if: env.UNITY_LICENSE != ''
        run: |
          echo "${UNITY_LICENSE}" > Unity_v${UNITY_VERSION}.ulf
          /opt/unity/Editor/Unity -batchmode -nographics -manualLicenseFile Unity_v${UNITY_VERSION}.ulf || true

      - name: Activate Unity License (Pro)
        if: env.UNITY_SERIAL != ''
        run: |
          /opt/unity/Editor/Unity -batchmode -nographics -username "$UNITY_EMAIL" -password "$UNITY_PASSWORD" -serial "$UNITY_SERIAL" -logFile /dev/stdout || true

      - name: Deactivate Unity License
        if: always()
        run: |
          /opt/unity/Editor/Unity -batchmode -nographics -returnlicense -logFile /dev/stdout || true
